/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { NormalizedFreelanceProject } from "../agent/freelancerTypes";
import { REMOTE_PLATFORMS_40 } from "./RemotePlatformsCatalog";
import { resolveDirectJobUrl } from "../utils/projectUrlHelper";

export function getInitialSeedProjectsForAll40Platforms(): NormalizedFreelanceProject[] {
  const nowISO = new Date().toISOString();

  const seedJobs: Omit<NormalizedFreelanceProject, "scrapeTimestamp">[] = [
    {
      id: "linkedin-01",
      title: "Senior Full-Stack React & Node Engineer",
      description: "Enterprise remote role designing high-throughput web portals, GraphQL microservices, and AI assistant interfaces.",
      skills: ["React", "TypeScript", "Node.js", "GraphQL", "Tailwind CSS"],
      budget: "$120,000 - $155,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 128,
      clientSpending: "$500,000+",
      location: "Remote (Global)",
      proposalCount: 14,
      urgency: "high",
      source: "LinkedIn Jobs",
      projectUrl: "https://www.linkedin.com/jobs",
      score: 95,
      scoreReasons: ["Direct employer verification", "High compensation match", "Verified skill fit"]
    },
    {
      id: "indeed-02",
      title: "Lead Cloud Infrastructure & DevOps Architect",
      description: "Remote cloud engineer to manage Cloud Run containers, CI/CD pipelines, Terraform infra, and Kubernetes clusters.",
      skills: ["DevOps", "Kubernetes", "Google Cloud", "Docker", "Terraform"],
      budget: "$130,000 - $160,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.8,
      clientReviews: 94,
      clientSpending: "$250,000+",
      location: "Remote (US/Canada)",
      proposalCount: 8,
      urgency: "high",
      source: "Indeed Remote",
      projectUrl: "https://www.indeed.com",
      score: 92,
      scoreReasons: ["Active enterprise recruiter", "Urgent hiring need"]
    },
    {
      id: "glassdoor-03",
      title: "Staff AI/ML Engineer (Gemini & LLM Applications)",
      description: "Build cutting-edge generative AI features, agentic workflows, and semantic search pipelines.",
      skills: ["Python", "Gemini API", "PyTorch", "Vector Databases", "TypeScript"],
      budget: "$140,000 - $180,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 5.0,
      clientReviews: 42,
      clientSpending: "$1,000,000+",
      location: "Remote",
      proposalCount: 19,
      urgency: "high",
      source: "Glassdoor Jobs",
      projectUrl: "https://www.glassdoor.com",
      score: 98,
      scoreReasons: ["Top tier salary", "Direct match with AI capabilities"]
    },
    {
      id: "flexjobs-04",
      title: "Senior Technical Copywriter & Documentation Lead",
      description: "Screened remote role for technical documentation, API guides, and developer documentation.",
      skills: ["Technical Writing", "API Docs", "Markdown", "Git", "SaaS"],
      budget: "$75 - $95 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.9,
      clientReviews: 31,
      clientSpending: "$120,000+",
      location: "Remote (Worldwide)",
      proposalCount: 5,
      urgency: "medium",
      source: "FlexJobs",
      projectUrl: "https://www.flexjobs.com",
      score: 88,
      scoreReasons: ["FlexJobs verified listing", "High hourly contract rate"]
    },
    {
      id: "weworkremotely-05",
      title: "Senior Frontend Engineer (React, Next.js, Motion)",
      description: "WeWorkRemotely featured posting for a fast-scaling SaaS startup. Focus on pixel-perfect UI and performance.",
      skills: ["React", "Next.js", "Motion", "Tailwind CSS", "TypeScript"],
      budget: "$110,000 - $140,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 67,
      clientSpending: "$300,000+",
      location: "Remote",
      proposalCount: 22,
      urgency: "high",
      source: "We Work Remotely",
      projectUrl: "https://weworkremotely.com",
      score: 94,
      scoreReasons: ["Verified startup opportunity", "Great stack alignment"]
    },
    {
      id: "remote_co-06",
      title: "Remote Site Reliability Engineer (SRE)",
      description: "Ensure high availability, uptime monitoring, and zero-downtime deployments for global client applications.",
      skills: ["SRE", "Linux", "Prometheus", "Grafana", "AWS"],
      budget: "$115,000 - $145,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.7,
      clientReviews: 18,
      clientSpending: "$180,000+",
      location: "Remote",
      proposalCount: 6,
      urgency: "medium",
      source: "Remote.co",
      projectUrl: "https://remote.co",
      score: 86,
      scoreReasons: ["Curated remote opening"]
    },
    {
      id: "upwork-07",
      title: "Build Real-Time AI Chatbot & Customer Support Hub",
      description: "Upwork verified client seeking expert developer to integrate Gemini API, WebSockets, and dashboard analytics.",
      skills: ["React", "Node.js", "Gemini API", "WebSockets", "Tailwind CSS"],
      budget: "$4,500 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.95,
      clientReviews: 83,
      clientSpending: "$150,000+",
      location: "Remote",
      proposalCount: 11,
      urgency: "high",
      source: "Upwork",
      projectUrl: "https://www.upwork.com",
      score: 96,
      scoreReasons: ["Payment verified client", "5-star rating", "Matching stack"]
    },
    {
      id: "freelancer-08",
      title: "Custom E-Commerce Platform API & Payment Integration",
      description: "Migrate legacy storefront to modern Node/Express microservices with Stripe payment gateway.",
      skills: ["Node.js", "Express", "Stripe API", "PostgreSQL", "React"],
      budget: "$3,200 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.8,
      clientReviews: 45,
      clientSpending: "$80,000+",
      location: "Remote",
      proposalCount: 15,
      urgency: "medium",
      source: "Freelancer.com",
      projectUrl: "https://www.freelancer.com",
      score: 89,
      scoreReasons: ["High review score", "Clear project scope"]
    },
    {
      id: "fiverr-09",
      title: "Fiverr Pro: Enterprise UI/UX Design System & Figma Tokens",
      description: "Design comprehensive dark/light mode UI kit for fintech web and mobile platforms.",
      skills: ["Figma", "UI/UX Design", "Design Systems", "Tailwind CSS"],
      budget: "$2,800 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 5.0,
      clientReviews: 110,
      clientSpending: "$200,000+",
      location: "Remote",
      proposalCount: 4,
      urgency: "high",
      source: "Fiverr / Fiverr Pro",
      projectUrl: "https://www.fiverr.com",
      score: 93,
      scoreReasons: ["Fiverr Pro verified client", "Low proposal count"]
    },
    {
      id: "guru-10",
      title: "Backend Specialist: SQLite to Cloud SQL Relational Migration",
      description: "Architect bidirectional database sync and migration service for distributed enterprise applets.",
      skills: ["PostgreSQL", "SQLite", "Node.js", "TypeScript", "Drizzle ORM"],
      budget: "$65 - $85 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.9,
      clientReviews: 29,
      clientSpending: "$95,000+",
      location: "Remote",
      proposalCount: 7,
      urgency: "medium",
      source: "Guru",
      projectUrl: "https://www.guru.com",
      score: 90,
      scoreReasons: ["Good hourly rate", "High match score"]
    },
    {
      id: "toptal-11",
      title: "Toptal Elite: Senior System Architect (Distributed Systems)",
      description: "Exclusive Toptal client hiring lead architect for multi-region microservices infrastructure.",
      skills: ["System Architecture", "Node.js", "Go", "Docker", "Cloud SQL"],
      budget: "$110 - $140 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 5.0,
      clientReviews: 210,
      clientSpending: "$2,000,000+",
      location: "Remote (Global)",
      proposalCount: 3,
      urgency: "high",
      source: "Toptal",
      projectUrl: "https://www.toptal.com",
      score: 99,
      scoreReasons: ["Premium hourly rate", "Toptal vetted enterprise"]
    },
    {
      id: "wellfound-12",
      title: "Founding Engineer @ AI Health Tech Startup",
      description: "Wellfound (AngelList) job opening: Lead frontend and AI integrations for YC-backed healthcare startup.",
      skills: ["React", "TypeScript", "Gemini API", "Tailwind CSS", "Python"],
      budget: "$125,000 - $160,000 + 1.5% Equity",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 12,
      clientSpending: "$500,000+",
      location: "Remote",
      proposalCount: 18,
      urgency: "high",
      source: "Wellfound (AngelList)",
      projectUrl: "https://wellfound.com",
      score: 97,
      scoreReasons: ["Equity offered", "Founding team role"]
    },
    {
      id: "hubstaff_talent-13",
      title: "Senior Node.js & Express API Developer",
      description: "Hubstaff Talent contract for building scalable RESTful APIs, authentication middleware, and database ORMs.",
      skills: ["Node.js", "Express", "TypeScript", "REST APIs"],
      budget: "$50 - $70 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.8,
      clientReviews: 34,
      clientSpending: "$60,000+",
      location: "Remote",
      proposalCount: 9,
      urgency: "medium",
      source: "Hubstaff Talent",
      projectUrl: "https://talent.hubstaff.com",
      score: 87,
      scoreReasons: ["Zero fee platform", "Steady workload"]
    },
    {
      id: "simplyhired-14",
      title: "Full Stack Engineer - Cloud Native Solutions",
      description: "Build reactive web components and cloud microservices for international logistics clients.",
      skills: ["React", "Node.js", "Google Cloud", "Tailwind CSS"],
      budget: "$105,000 - $130,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.7,
      clientReviews: 50,
      clientSpending: "$400,000+",
      location: "Remote",
      proposalCount: 12,
      urgency: "medium",
      source: "SimplyHired",
      projectUrl: "https://www.simplyhired.com",
      score: 85,
      scoreReasons: ["Competitive base salary"]
    },
    {
      id: "remotive-15",
      title: "Senior React Engineer - Real-Time Analytics Dashboard",
      description: "Remotive contract: Develop high-frequency chart visualizers, Recharts components, and live WebSockets.",
      skills: ["React", "Recharts", "TypeScript", "WebSockets", "Tailwind CSS"],
      budget: "$90,000 - $125,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 78,
      clientSpending: "$350,000+",
      location: "Remote",
      proposalCount: 10,
      urgency: "high",
      source: "Remotive",
      projectUrl: "https://remotive.com",
      score: 93,
      scoreReasons: ["Remotive live API verified", "High match rating"]
    },
    {
      id: "virtual_vocations-16",
      title: "Executive Virtual Assistant & Operations Coordinator",
      description: "Manage calendar scheduling, travel arrangements, customer email triage, and client follow-ups.",
      skills: ["Virtual Assistance", "Email Triage", "Calendar Management", "Customer Support"],
      budget: "$30 - $45 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.8,
      clientReviews: 22,
      clientSpending: "$40,000+",
      location: "Remote",
      proposalCount: 6,
      urgency: "medium",
      source: "Virtual Vocations",
      projectUrl: "https://www.virtualvocations.com",
      score: 82,
      scoreReasons: ["Vetted telecommute role"]
    },
    {
      id: "working_nomads-17",
      title: "Mobile App Developer (React Native & Cross-Platform)",
      description: "Working Nomads listing for building iOS/Android cross-platform apps with offline SQLite sync.",
      skills: ["React Native", "TypeScript", "SQLite", "Mobile UI"],
      budget: "$80,000 - $110,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.85,
      clientReviews: 19,
      clientSpending: "$110,000+",
      location: "Remote (Global)",
      proposalCount: 8,
      urgency: "medium",
      source: "Working Nomads",
      projectUrl: "https://www.workingnomads.com",
      score: 88,
      scoreReasons: ["Nomad friendly flexible schedule"]
    },
    {
      id: "hired-18",
      title: "Staff Software Engineer - Distributed Storage & DB Engines",
      description: "Hired reverse marketplace match: Direct interview invitations from top tech firms.",
      skills: ["TypeScript", "PostgreSQL", "Distributed Systems", "Node.js"],
      budget: "$150,000 - $190,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 5.0,
      clientReviews: 310,
      clientSpending: "$5,000,000+",
      location: "Remote",
      proposalCount: 2,
      urgency: "high",
      source: "Hired",
      projectUrl: "https://hired.com",
      score: 98,
      scoreReasons: ["Direct employer application", "Top salary bracket"]
    },
    {
      id: "cloudpeeps-19",
      title: "Growth Marketer & Community Manager",
      description: "Drive user acquisition, organic social media growth, and developer community engagement.",
      skills: ["Growth Marketing", "Community Management", "SEO", "Content Strategy"],
      budget: "$45 - $65 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.7,
      clientReviews: 15,
      clientSpending: "$35,000+",
      location: "Remote",
      proposalCount: 5,
      urgency: "medium",
      source: "CloudPeeps",
      projectUrl: "https://www.cloudpeeps.com",
      score: 81,
      scoreReasons: ["Community focused contract"]
    },
    {
      id: "taskrabbit-20",
      title: "Remote Technical Helpdesk & Device Setup Specialist",
      description: "Provide remote technical assistance, software configuration, and IT setup support.",
      skills: ["Technical Support", "Helpdesk", "IT Troubleshooting", "Software Setup"],
      budget: "$35 - $50 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.9,
      clientReviews: 52,
      clientSpending: "$25,000+",
      location: "Remote",
      proposalCount: 4,
      urgency: "high",
      source: "TaskRabbit",
      projectUrl: "https://taskrabbit.com",
      score: 80,
      scoreReasons: ["Immediate availability demand"]
    },
    {
      id: "talent_com-21",
      title: "Lead Frontend Developer - Enterprise SaaS Portal",
      description: "Build modular web components, accessible UI elements, and high-performance SPA views.",
      skills: ["React", "TypeScript", "Tailwind CSS", "A11y"],
      budget: "$100,000 - $130,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.8,
      clientReviews: 40,
      clientSpending: "$220,000+",
      location: "Remote",
      proposalCount: 11,
      urgency: "medium",
      source: "Talent.com",
      projectUrl: "https://www.talent.com",
      score: 89,
      scoreReasons: ["Solid company profile"]
    },
    {
      id: "remoteok-22",
      title: "Full Stack Engineer (Node, Express, React & AI)",
      description: "RemoteOK featured role: Build autonomous agent workflows, REST API services, and AI Studio integrations.",
      skills: ["React", "Node.js", "Express", "Gemini API", "Tailwind CSS"],
      budget: "$110,000 - $145,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.95,
      clientReviews: 140,
      clientSpending: "$800,000+",
      location: "Remote",
      proposalCount: 16,
      urgency: "high",
      source: "RemoteOK",
      projectUrl: "https://remoteok.com",
      score: 96,
      scoreReasons: ["RemoteOK top listing", "Stack match 100%"]
    },
    {
      id: "dremote-23",
      title: "Senior Backend Developer - Microservices & SQLite",
      description: "DRemote listing: Build resilient SQLite and PostgreSQL database adapters for desktop/cloud apps.",
      skills: ["Node.js", "TypeScript", "SQLite", "PostgreSQL", "Docker"],
      budget: "$85,000 - $115,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.75,
      clientReviews: 24,
      clientSpending: "$130,000+",
      location: "Remote",
      proposalCount: 7,
      urgency: "medium",
      source: "DRemote (Dremotech)",
      projectUrl: "https://dremote.io",
      score: 88,
      scoreReasons: ["Specific SQLite expertise requested"]
    },
    {
      id: "jooble-24",
      title: "International Web Developer & WordPress Specialist",
      description: "Maintain international web properties, custom PHP/Node plugins, and cloud deployments.",
      skills: ["Web Development", "PHP", "Node.js", "CSS", "MySQL"],
      budget: "$60,000 - $85,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.6,
      clientReviews: 30,
      clientSpending: "$90,000+",
      location: "Remote",
      proposalCount: 13,
      urgency: "low",
      source: "Jooble",
      projectUrl: "https://jooble.org",
      score: 81,
      scoreReasons: ["Global search vacancy"]
    },
    {
      id: "stackoverflow_jobs-25",
      title: "Senior Systems Engineer - High Performance Algorithms",
      description: "Develop low-latency data processing pipelines, caching algorithms, and queue workers.",
      skills: ["C++", "Rust", "Node.js", "Algorithms", "Performance"],
      budget: "$135,000 - $170,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.95,
      clientReviews: 88,
      clientSpending: "$1,500,000+",
      location: "Remote",
      proposalCount: 9,
      urgency: "high",
      source: "Stack Overflow Jobs",
      projectUrl: "https://stackoverflow.com/jobs",
      score: 94,
      scoreReasons: ["Technical depth match"]
    },
    {
      id: "jobspresso-26",
      title: "Lead UI Developer - Design System & Component Library",
      description: "Jobspresso curated role: Create modular React component libraries using Tailwind CSS and Radix UI.",
      skills: ["React", "TypeScript", "Tailwind CSS", "Design Systems"],
      budget: "$95,000 - $125,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 43,
      clientSpending: "$210,000+",
      location: "Remote",
      proposalCount: 8,
      urgency: "medium",
      source: "Jobspresso",
      projectUrl: "https://jobspresso.co",
      score: 91,
      scoreReasons: ["Curated quality listing"]
    },
    {
      id: "onlinejobs_ph-27",
      title: "Senior Full Stack Web Developer & Virtual Specialist",
      description: "OnlineJobs.ph contract: Long-term full-time remote position for web development and automated systems.",
      skills: ["React", "Node.js", "Express", "MySQL", "Tailwind CSS"],
      budget: "$2,000 - $3,500 / mo",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.85,
      clientReviews: 56,
      clientSpending: "$75,000+",
      location: "Remote (Philippines / Global)",
      proposalCount: 10,
      urgency: "medium",
      source: "OnlineJobs.ph",
      projectUrl: "https://www.onlinejobs.ph",
      score: 86,
      scoreReasons: ["Dedicated long-term contract"]
    },
    {
      id: "simplyhired_global-28",
      title: "Cloud Database Engineer & Migration Architect",
      description: "Manage hybrid database deployments across PostgreSQL, Firestore, and SQLite backends.",
      skills: ["PostgreSQL", "Firestore", "SQLite", "Node.js", "Docker"],
      budget: "$110,000 - $140,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.8,
      clientReviews: 37,
      clientSpending: "$310,000+",
      location: "Remote",
      proposalCount: 7,
      urgency: "high",
      source: "SimplyHired Global",
      projectUrl: "https://www.simplyhired.com/search?q=remote",
      score: 92,
      scoreReasons: ["Multi-database architecture fit"]
    },
    {
      id: "themuse-29",
      title: "Lead Frontend Engineer - Inclusive Product Experience",
      description: "The Muse company showcase role: Drive accessible UI engineering and responsive design standards.",
      skills: ["React", "TypeScript", "Tailwind CSS", "Accessibility"],
      budget: "$115,000 - $140,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 61,
      clientSpending: "$450,000+",
      location: "Remote",
      proposalCount: 12,
      urgency: "medium",
      source: "The Muse",
      projectUrl: "https://www.themuse.com",
      score: 89,
      scoreReasons: ["Vetted company culture match"]
    },
    {
      id: "skipthedrive-30",
      title: "Work-From-Home Technical Support & QA Automation Specialist",
      description: "Automate web testing, end-to-end integration flows, and customer technical support ticketing.",
      skills: ["QA Automation", "Playwright", "TypeScript", "Customer Support"],
      budget: "$40 - $60 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.75,
      clientReviews: 28,
      clientSpending: "$55,000+",
      location: "Remote",
      proposalCount: 5,
      urgency: "low",
      source: "Skip The Drive",
      projectUrl: "https://www.skipthedrive.com",
      score: 83,
      scoreReasons: ["Flexible work-from-home position"]
    },
    {
      id: "zirtual-31",
      title: "Dedicated Executive Virtual Assistant & Workflow Manager",
      description: "Assist CEO with automated email dispatches, calendar sync, travel logistics, and client correspondence.",
      skills: ["Executive Assistance", "Workflow Automation", "Email Management"],
      budget: "$35 - $50 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.9,
      clientReviews: 39,
      clientSpending: "$65,000+",
      location: "Remote",
      proposalCount: 3,
      urgency: "high",
      source: "Zirtual",
      projectUrl: "https://www.zirtual.com",
      score: 84,
      scoreReasons: ["High client rating"]
    },
    {
      id: "justremote-32",
      title: "Senior React Native Mobile App Engineer",
      description: "JustRemote hidden job discovery: Build offline-first mobile apps for cross-platform logistics.",
      skills: ["React Native", "TypeScript", "Mobile UI", "Offline Sync"],
      budget: "$105,000 - $135,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.85,
      clientReviews: 22,
      clientSpending: "$170,000+",
      location: "Remote",
      proposalCount: 6,
      urgency: "medium",
      source: "JustRemote",
      projectUrl: "https://justremote.co",
      score: 90,
      scoreReasons: ["Hidden unadvertised opening"]
    },
    {
      id: "hireable-33",
      title: "Backend API Engineer (Node.js & Microservices)",
      description: "Develop resilient API endpoints, rate limiting middleware, and payload validation tools.",
      skills: ["Node.js", "Express", "TypeScript", "REST APIs"],
      budget: "$90,000 - $120,000 / yr",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.7,
      clientReviews: 33,
      clientSpending: "$190,000+",
      location: "Remote",
      proposalCount: 14,
      urgency: "low",
      source: "Hireable",
      projectUrl: "https://www.hireable.com",
      score: 86,
      scoreReasons: ["Fast match process"]
    },
    {
      id: "remoteworkhub-34",
      title: "Global Nomad Web Developer & UI Engineer",
      description: "Contract position for building high-performance landing pages and interactive SaaS dashboards.",
      skills: ["React", "TypeScript", "Tailwind CSS", "Motion"],
      budget: "$55 - $80 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.8,
      clientReviews: 17,
      clientSpending: "$85,000+",
      location: "Remote (Global)",
      proposalCount: 8,
      urgency: "medium",
      source: "Remote Work Hub",
      projectUrl: "https://remoteworkhub.com",
      score: 87,
      scoreReasons: ["Global contract flexibility"]
    },
    {
      id: "jobbatical-35",
      title: "International Senior Full Stack Developer",
      description: "Jobbatical tech placement: Opportunity for remote work or optional EU relocation assistance.",
      skills: ["Node.js", "React", "TypeScript", "Docker"],
      budget: "€80,000 - €110,000 / yr",
      currency: "EUR",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 48,
      clientSpending: "$600,000+",
      location: "Remote / EU Relocation Option",
      proposalCount: 11,
      urgency: "medium",
      source: "Jobbatical",
      projectUrl: "https://jobbatical.com",
      score: 91,
      scoreReasons: ["International relocation sponsorship option"]
    },
    {
      id: "freelancewritinggigs-36",
      title: "Senior Technical Writer & Developer Advocate Content",
      description: "Write in-depth developer tutorials, code samples, and architecture breakdown articles.",
      skills: ["Technical Writing", "Developer Advocacy", "Markdown", "Git"],
      budget: "$400 - $800 per Article",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.95,
      clientReviews: 64,
      clientSpending: "$110,000+",
      location: "Remote",
      proposalCount: 4,
      urgency: "high",
      source: "Freelance Writing Gigs",
      projectUrl: "https://www.freelancewritinggigs.com",
      score: 92,
      scoreReasons: ["High per-article rate", "Direct developer content match"]
    },
    {
      id: "contentwritingjobs-37",
      title: "SEO & B2B SaaS Content Strategy Writer",
      description: "Craft high-ranking SEO articles, whitepapers, and product guides for enterprise software clients.",
      skills: ["Content Writing", "SEO", "Copywriting", "B2B SaaS"],
      budget: "$50 - $75 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.85,
      clientReviews: 27,
      clientSpending: "$70,000+",
      location: "Remote",
      proposalCount: 6,
      urgency: "medium",
      source: "Content Writing Jobs",
      projectUrl: "https://contentwritingjobs.com",
      score: 88,
      scoreReasons: ["Steady contract work"]
    },
    {
      id: "problogger-38",
      title: "ProBlogger: AI & Tech Blog Editor & Lead Writer",
      description: "Manage editorial calendar, write blog posts on artificial intelligence, LLMs, and agentic workflows.",
      skills: ["Blogging", "AI Trends", "Content Strategy", "Editing"],
      budget: "$3,000 - $4,500 / mo",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 73,
      clientSpending: "$140,000+",
      location: "Remote",
      proposalCount: 9,
      urgency: "high",
      source: "ProBlogger Jobs",
      projectUrl: "https://problogger.com/jobs",
      score: 93,
      scoreReasons: ["ProBlogger top listing", "Monthly retainer contract"]
    },
    {
      id: "behance-39",
      title: "Behance Creative: Senior UI/UX Designer (Dark Luxury Theme)",
      description: "Design bespoke web app interfaces, interactive prototypes, and luxury design systems.",
      skills: ["Figma", "UI/UX Design", "Prototyping", "Design Systems"],
      budget: "$3,500 - $6,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 5.0,
      clientReviews: 36,
      clientSpending: "$250,000+",
      location: "Remote",
      proposalCount: 5,
      urgency: "high",
      source: "Behance Jobs",
      projectUrl: "https://www.behance.net/joblist",
      score: 95,
      scoreReasons: ["Behance top creative project", "Generous budget"]
    },
    {
      id: "designhill-40",
      title: "Designhill Pro: Brand Identity & Custom Logo System",
      description: "Create complete brand identity, typography guidelines, vector assets, and brand book.",
      skills: ["Brand Identity", "Graphic Design", "Logo Design", "Illustrator"],
      budget: "$1,800 - $3,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.8,
      clientReviews: 81,
      clientSpending: "$120,000+",
      location: "Remote",
      proposalCount: 12,
      urgency: "medium",
      source: "Designhill",
      projectUrl: "https://www.designhill.com",
      score: 87,
      scoreReasons: ["Verified client contest/contract"]
    },
    {
      id: "aaditech-m365-41",
      title: "Enterprise Microsoft 365 & Exchange Online Migration Consultant",
      description: "Seeking an experienced IT infrastructure consultant to lead a cloud migration project transitioning 450 users from legacy on-premise mail to Microsoft 365 and Exchange Online. Must have strong PowerShell and AD sync background.",
      skills: ["Microsoft 365", "Exchange Online", "Cloud Migration", "Active Directory", "System Administration"],
      budget: "$6,500 - $9,500 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.95,
      clientReviews: 54,
      clientSpending: "$380,000+",
      location: "Remote (Global)",
      proposalCount: 4,
      urgency: "high",
      source: "Upwork Enterprise",
      projectUrl: "https://www.upwork.com",
      score: 96,
      scoreReasons: ["Verified M365 enterprise contract", "High budget"]
    },
    {
      id: "aaditech-windows-server-42",
      title: "Windows Server 2022 & Active Directory Infrastructure Administrator",
      description: "Configure, harden, and manage distributed Active Directory domain controllers, Group Policies, DNS/DHCP, and hybrid Windows Server infrastructure for a multi-branch firm.",
      skills: ["Windows Server", "Active Directory", "System Administration", "DNS", "Cybersecurity"],
      budget: "$70 - $95 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.9,
      clientReviews: 39,
      clientSpending: "$190,000+",
      location: "Remote",
      proposalCount: 3,
      urgency: "high",
      source: "Spiceworks",
      projectUrl: "https://community.spiceworks.com/jobs",
      score: 94,
      scoreReasons: ["Direct IT infrastructure need", "Long term retainer"]
    },
    {
      id: "aaditech-network-sec-43",
      title: "Senior Network Engineer — Fortinet Firewall, Site-to-Site VPN & Cisco LAN/WAN",
      description: "Urgent deployment of FortiGate firewalls, IPsec VPN tunnels, VLAN segmentation, and network engineering monitoring for corporate offices.",
      skills: ["Network Engineering", "Firewall", "VPN", "Cybersecurity", "System Administration"],
      budget: "$80 - $110 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 5.0,
      clientReviews: 62,
      clientSpending: "$450,000+",
      location: "Remote / Hybrid (Mumbai friendly)",
      proposalCount: 5,
      urgency: "high",
      source: "LinkedIn Jobs",
      projectUrl: "https://www.linkedin.com/jobs",
      score: 95,
      scoreReasons: ["High-paying network engineering role", "Urgent start"]
    },
    {
      id: "aaditech-remote-it-44",
      title: "Remote IT Support & Systems Helpdesk Specialist (Tier 2/3)",
      description: "Provide dedicated remote IT support for enterprise workstations, Microsoft 365 troubleshooting, Active Directory user permissions, and VPN access resolution.",
      skills: ["Remote IT Support", "Windows Server", "Active Directory", "Microsoft 365", "Troubleshooting"],
      budget: "$2,800 - $4,200 / mo",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.85,
      clientReviews: 47,
      clientSpending: "$160,000+",
      location: "Remote (Pan-India & Global)",
      proposalCount: 7,
      urgency: "medium",
      source: "Indeed Remote",
      projectUrl: "https://www.indeed.com",
      score: 91,
      scoreReasons: ["Monthly steady support retainer"]
    },
    {
      id: "aaditech-ai-automation-45",
      title: "IT Infrastructure Automation Engineer — Python & AI Workflows",
      description: "Automate repetitive server maintenance routines, Active Directory auditing, ticket categorization, and health check monitoring using Python and generative AI scripts.",
      skills: ["AI Automation", "Python Automation", "System Administration", "Networking", "DevOps"],
      budget: "$5,000 - $8,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 29,
      clientSpending: "$210,000+",
      location: "Remote",
      proposalCount: 3,
      urgency: "high",
      source: "Guru",
      projectUrl: "https://www.guru.com",
      score: 93,
      scoreReasons: ["AI automation synergy", "Enterprise client"]
    },
    {
      id: "aaditech-cybersecurity-46",
      title: "Cybersecurity & Identity Access Management (IAM) Specialist",
      description: "Perform identity security assessment, Multi-Factor Authentication (MFA) enforcement across Microsoft 365, Active Directory permission auditing, and firewall rule review.",
      skills: ["Cybersecurity", "Active Directory", "Microsoft 365", "Firewall", "VPN"],
      budget: "$85 - $125 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.95,
      clientReviews: 78,
      clientSpending: "$600,000+",
      location: "Remote",
      proposalCount: 4,
      urgency: "high",
      source: "FlexJobs",
      projectUrl: "https://www.flexjobs.com",
      score: 97,
      scoreReasons: ["Cybersecurity verified premium contract"]
    },
    {
      id: "aaditech-cloud-migration-47",
      title: "Hybrid Cloud Migration Engineer — On-Prem AD to M365 Cloud",
      description: "Design and implement hybrid identity federation with Azure AD Connect, migrate local file shares to SharePoint/OneDrive, and decommission legacy on-prem systems.",
      skills: ["Cloud Migration", "Microsoft 365", "Active Directory", "Windows Server", "Exchange Online"],
      budget: "$4,500 - $7,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.8,
      clientReviews: 33,
      clientSpending: "$130,000+",
      location: "Remote (Mumbai / Global)",
      proposalCount: 5,
      urgency: "medium",
      source: "Freelancer.com",
      projectUrl: "https://www.freelancer.com",
      score: 92,
      scoreReasons: ["Direct match for IT Cloud Migration"]
    },
    {
      id: "design-figma-48",
      title: "99designs Pro: Mobile App UI/UX & Figma Design System Lead",
      description: "Craft modern, accessible mobile app UI/UX, responsive layouts, and interactive design system components in Figma.",
      skills: ["Figma", "UI/UX", "Design Systems", "Prototyping", "Mobile Design"],
      budget: "$3,000 - $5,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 44,
      clientSpending: "$180,000+",
      location: "Remote",
      proposalCount: 6,
      urgency: "high",
      source: "99designs",
      projectUrl: "https://99designs.com",
      score: 94,
      scoreReasons: ["Direct Design & Creative match"]
    },
    {
      id: "aaditech-infra-49",
      title: "Microsoft 365 Defender & Advanced Threat Protection (ATP) Specialist",
      description: "Configure Microsoft Defender for Endpoint, Office 365 email anti-phishing policies, Safe Attachments, and Conditional Access rules.",
      skills: ["Microsoft 365", "Cybersecurity", "Exchange Online", "Active Directory", "Remote IT Support"],
      budget: "$5,500 - $8,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 53,
      clientSpending: "$310,000+",
      location: "Remote (Global)",
      proposalCount: 4,
      urgency: "high",
      source: "Spiceworks Community",
      projectUrl: "https://community.spiceworks.com",
      score: 96,
      scoreReasons: ["Enterprise M365 security lead"]
    },
    {
      id: "aaditech-infra-50",
      title: "Windows Server 2022 & Hyper-V Cluster Administrator",
      description: "Manage, optimize, and patch Windows Server 2019/2022 failover clusters, Hyper-V virtual machines, and SAN/NAS storage replication.",
      skills: ["Windows Server", "System Administration", "Active Directory", "Networking", "Remote IT Support"],
      budget: "$65 - $95 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 5.0,
      clientReviews: 41,
      clientSpending: "$240,000+",
      location: "Remote",
      proposalCount: 5,
      urgency: "high",
      source: "Upwork Enterprise",
      projectUrl: "https://www.upwork.com",
      score: 95,
      scoreReasons: ["Direct match for Windows Server & Hyper-V"]
    },
    {
      id: "aaditech-infra-51",
      title: "Active Directory Domain Controller & Group Policy (GPO) Architect",
      description: "Audit existing Active Directory forest, consolidate legacy Organizational Units (OUs), redesign Group Policies for security compliance, and prepare for Azure AD sync.",
      skills: ["Active Directory", "Windows Server", "System Administration", "Cybersecurity", "Cloud Migration"],
      budget: "$4,000 - $6,500 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.8,
      clientReviews: 36,
      clientSpending: "$180,000+",
      location: "Remote",
      proposalCount: 3,
      urgency: "high",
      source: "LinkedIn IT Jobs",
      projectUrl: "https://www.linkedin.com/jobs",
      score: 94,
      scoreReasons: ["AD & GPO architectural overhaul"]
    },
    {
      id: "aaditech-infra-52",
      title: "Network Security Engineer — Fortinet & Palo Alto Next-Gen Firewalls",
      description: "Deploy, manage, and harden FortiGate and Palo Alto firewalls, implement intrusion prevention (IPS), configure SSL inspection, and monitor network traffic.",
      skills: ["Firewall", "Network Engineering", "VPN", "Cybersecurity", "System Administration"],
      budget: "$75 - $110 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.95,
      clientReviews: 62,
      clientSpending: "$450,000+",
      location: "Remote",
      proposalCount: 4,
      urgency: "high",
      source: "Indeed Remote IT",
      projectUrl: "https://www.indeed.com",
      score: 97,
      scoreReasons: ["Verified Fortinet & Palo Alto expertise"]
    },
    {
      id: "aaditech-infra-53",
      title: "24/7 Remote IT Support & System Administrator (Tier 2/3 MSP)",
      description: "Provide comprehensive Tier 2/3 technical helpdesk support for remote enterprise workforce covering Windows, M365, VPN access, Outlook, and Active Directory resets.",
      skills: ["Remote IT Support", "System Administration", "Microsoft 365", "Windows Server", "VPN"],
      budget: "$45 - $65 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.85,
      clientReviews: 89,
      clientSpending: "$520,000+",
      location: "Remote (24/7 Rotation)",
      proposalCount: 7,
      urgency: "high",
      source: "Guru IT Network",
      projectUrl: "https://www.guru.com",
      score: 93,
      scoreReasons: ["Long-term MSP contract opportunity"]
    },
    {
      id: "aaditech-infra-54",
      title: "Exchange Online Mailbox & Tenant-to-Tenant Migration Consultant",
      description: "Execute merger and acquisition tenant-to-tenant Microsoft 365 migration for 450+ user mailboxes, distribution lists, calendar permissions, and Teams chats.",
      skills: ["Exchange Online", "Microsoft 365", "Cloud Migration", "Active Directory", "System Administration"],
      budget: "$6,000 - $9,500 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 5.0,
      clientReviews: 24,
      clientSpending: "$380,000+",
      location: "Remote",
      proposalCount: 3,
      urgency: "high",
      source: "Upwork Enterprise",
      projectUrl: "https://www.upwork.com",
      score: 96,
      scoreReasons: ["High-paying M365 tenant migration"]
    },
    {
      id: "aaditech-infra-55",
      title: "Azure Virtual Desktop (AVD) & Microsoft Intune MDM Specialist",
      description: "Deploy Microsoft Intune policy configurations, Autopilot provisioning for Windows laptops, and scale Azure Virtual Desktop host pools for remote staff.",
      skills: ["Microsoft 365", "System Administration", "Windows Server", "Cloud Migration", "Remote IT Support"],
      budget: "$70 - $105 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.9,
      clientReviews: 47,
      clientSpending: "$290,000+",
      location: "Remote",
      proposalCount: 5,
      urgency: "high",
      source: "LinkedIn IT Jobs",
      projectUrl: "https://www.linkedin.com/jobs",
      score: 95,
      scoreReasons: ["Enterprise Intune & AVD requirement"]
    },
    {
      id: "aaditech-infra-56",
      title: "Enterprise Cisco Catalyst & Meraki Network Infrastructure Engineer",
      description: "Configure VLANs, Spanning Tree, BGP/OSPF routing protocols, Cisco Meraki dashboard telemetry, and site-to-site VPN mesh across 6 regional office sites.",
      skills: ["Network Engineering", "Networking", "VPN", "Firewall", "System Administration"],
      budget: "$80 - $115 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.9,
      clientReviews: 58,
      clientSpending: "$410,000+",
      location: "Remote",
      proposalCount: 4,
      urgency: "high",
      source: "Freelancer.com",
      projectUrl: "https://www.freelancer.com",
      score: 96,
      scoreReasons: ["Cisco & Meraki multi-site architecture"]
    },
    {
      id: "aaditech-infra-57",
      title: "Veeam Backup & Disaster Recovery (BCDR) Implementation Specialist",
      description: "Design automated backup retention policies, off-site cloud replication, and annual disaster recovery failover drill using Veeam Backup & Replication for Windows Server workloads.",
      skills: ["Windows Server", "System Administration", "Cloud Migration", "Cybersecurity", "Remote IT Support"],
      budget: "$4,500 - $7,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.8,
      clientReviews: 31,
      clientSpending: "$190,000+",
      location: "Remote",
      proposalCount: 3,
      urgency: "medium",
      source: "Guru",
      projectUrl: "https://www.guru.com",
      score: 92,
      scoreReasons: ["Critical disaster recovery initiative"]
    },
    {
      id: "aaditech-infra-58",
      title: "Python & PowerShell Automation Engineer for IT System Administration",
      description: "Build robust automation scripts in Python and PowerShell to automate user onboarding in Active Directory, Office 365 license assignment, and server uptime monitoring.",
      skills: ["Python Automation", "AI Automation", "System Administration", "Active Directory", "Microsoft 365"],
      budget: "$60 - $85 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 5.0,
      clientReviews: 67,
      clientSpending: "$330,000+",
      location: "Remote",
      proposalCount: 6,
      urgency: "high",
      source: "Dice IT Jobs",
      projectUrl: "https://www.dice.com",
      score: 94,
      scoreReasons: ["PowerShell and Python sysadmin automation"]
    },
    {
      id: "aaditech-infra-59",
      title: "SonicWall & pfSense Site-to-Site VPN Tunneling Specialist",
      description: "Establish and stabilize IPsec IKEv2 site-to-site VPN tunnels between corporate headquarters and branch offices using SonicWall NSA and Netgate pfSense firewalls.",
      skills: ["VPN", "Firewall", "Network Engineering", "Networking", "Remote IT Support"],
      budget: "$2,500 - $4,200 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.85,
      clientReviews: 29,
      clientSpending: "$140,000+",
      location: "Remote",
      proposalCount: 2,
      urgency: "high",
      source: "PeoplePerHour",
      projectUrl: "https://www.peopleperhour.com",
      score: 93,
      scoreReasons: ["Direct IPsec VPN contract"]
    },
    {
      id: "aaditech-infra-60",
      title: "Microsoft Entra ID (Azure AD) Single Sign-On (SSO) & SAML Integrator",
      description: "Configure Enterprise Applications in Microsoft Entra ID with SAML 2.0 and OIDC for Single Sign-On, SCIM automated user provisioning, and Conditional Access.",
      skills: ["Microsoft 365", "Active Directory", "Cybersecurity", "System Administration", "Cloud Migration"],
      budget: "$3,800 - $6,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.95,
      clientReviews: 44,
      clientSpending: "$275,000+",
      location: "Remote",
      proposalCount: 4,
      urgency: "high",
      source: "Spiceworks",
      projectUrl: "https://community.spiceworks.com",
      score: 95,
      scoreReasons: ["Identity Federation & SSO mastery"]
    },
    {
      id: "aaditech-infra-61",
      title: "Senior Windows System Administrator — Patch Management & Active Directory",
      description: "Oversee monthly WSUS/Intune patch management across 300+ Windows Servers and workstations, enforce GPO baselines, and resolve server performance bottlenecks.",
      skills: ["Windows Server", "System Administration", "Active Directory", "Remote IT Support", "Networking"],
      budget: "$55 - $80 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.9,
      clientReviews: 52,
      clientSpending: "$360,000+",
      location: "Remote",
      proposalCount: 5,
      urgency: "high",
      source: "LinkedIn IT Jobs",
      projectUrl: "https://www.linkedin.com/jobs",
      score: 94,
      scoreReasons: ["Long-term Windows SysAdmin position"]
    },
    {
      id: "aaditech-infra-62",
      title: "Remote IT Helpdesk Lead — Office 365, Teams & Hardware Troubleshooting",
      description: "Lead remote IT helpdesk team providing first-contact resolution for M365 issues, Microsoft Teams rooms, Outlook sync errors, and printer/network connectivity.",
      skills: ["Remote IT Support", "Microsoft 365", "System Administration", "Networking", "Exchange Online"],
      budget: "$40 - $60 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.75,
      clientReviews: 73,
      clientSpending: "$490,000+",
      location: "Remote",
      proposalCount: 6,
      urgency: "high",
      source: "SkipTheDrive",
      projectUrl: "https://www.skipthedrive.com",
      score: 91,
      scoreReasons: ["Remote IT helpdesk leadership role"]
    },
    {
      id: "aaditech-infra-63",
      title: "VMware ESXi to Hyper-V / Cloud Infrastructure Migration Engineer",
      description: "Migrate legacy VMware vSphere infrastructure to Microsoft Hyper-V and Azure IaaS, converting VMDK disks to VHDX with minimal downtime.",
      skills: ["Cloud Migration", "Windows Server", "System Administration", "Networking", "Remote IT Support"],
      budget: "$5,000 - $8,500 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 5.0,
      clientReviews: 38,
      clientSpending: "$320,000+",
      location: "Remote",
      proposalCount: 4,
      urgency: "high",
      source: "Upwork Enterprise",
      projectUrl: "https://www.upwork.com",
      score: 95,
      scoreReasons: ["Virtualization migration contract"]
    },
    {
      id: "aaditech-infra-64",
      title: "Cybersecurity Incident Response & Endpoint Security (EDR) Analyst",
      description: "Analyze endpoint alerts, investigate potential malware infections, configure SentinelOne/CrowdStrike EDR agents, and enforce zero-trust security postures.",
      skills: ["Cybersecurity", "System Administration", "Firewall", "Active Directory", "Remote IT Support"],
      budget: "$70 - $100 / hr",
      currency: "USD",
      hourlyOrFixed: "hourly",
      clientRating: 4.9,
      clientReviews: 49,
      clientSpending: "$510,000+",
      location: "Remote",
      proposalCount: 3,
      urgency: "high",
      source: "FlexJobs",
      projectUrl: "https://www.flexjobs.com",
      score: 96,
      scoreReasons: ["High-priority Cybersecurity contract"]
    },
    {
      id: "aaditech-infra-65",
      title: "Network Penetration Testing & Vulnerability Remediation Consultant",
      description: "Perform comprehensive internal and external network vulnerability scans, assess firewall rule weaknesses, and provide technical remediation roadmaps.",
      skills: ["Cybersecurity", "Network Engineering", "Firewall", "Networking", "System Administration"],
      budget: "$6,500 - $11,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 5.0,
      clientReviews: 32,
      clientSpending: "$400,000+",
      location: "Remote",
      proposalCount: 2,
      urgency: "high",
      source: "Spiceworks",
      projectUrl: "https://community.spiceworks.com",
      score: 97,
      scoreReasons: ["High-value security audit project"]
    },
    {
      id: "aaditech-infra-66",
      title: "Ubiquiti UniFi Enterprise Wi-Fi & Multi-Branch Network Deployment",
      description: "Configure UniFi Dream Machine Pros, Wi-Fi 6 access points, guest portal isolation, and VLAN tagging across 4 retail branch locations.",
      skills: ["Networking", "Network Engineering", "Firewall", "Remote IT Support", "System Administration"],
      budget: "$2,800 - $4,500 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.8,
      clientReviews: 22,
      clientSpending: "$110,000+",
      location: "Remote",
      proposalCount: 4,
      urgency: "medium",
      source: "Freelancer.com",
      projectUrl: "https://www.freelancer.com",
      score: 92,
      scoreReasons: ["Ubiquiti UniFi network setup"]
    },
    {
      id: "design-creative-67",
      title: "Behance Showcase: Corporate Tech Brand Identity & Vector Logo Suite",
      description: "Design comprehensive corporate brand identity guideline, minimalist vector logos, typographic hierarchy, and icon library in Figma & Illustrator.",
      skills: ["Logo Design", "Figma", "UI/UX", "Brand Identity", "Vector Illustration"],
      budget: "$2,500 - $4,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.95,
      clientReviews: 61,
      clientSpending: "$230,000+",
      location: "Remote",
      proposalCount: 5,
      urgency: "high",
      source: "Behance",
      projectUrl: "https://www.behance.net",
      score: 94,
      scoreReasons: ["Design & Creative premium brand overhaul"]
    },
    {
      id: "design-creative-68",
      title: "Designhill Expert: Enterprise SaaS Web Portal UI/UX Redesign in Figma",
      description: "Redesign complex B2B SaaS web portal dashboards, user flows, navigation menus, and data visualization cards with Figma components.",
      skills: ["UI/UX", "Figma", "Design Systems", "Prototyping", "User Experience"],
      budget: "$3,500 - $6,000 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.9,
      clientReviews: 45,
      clientSpending: "$190,000+",
      location: "Remote",
      proposalCount: 6,
      urgency: "high",
      source: "Designhill",
      projectUrl: "https://www.designhill.com",
      score: 95,
      scoreReasons: ["SaaS Figma UI/UX overhaul"]
    },
    {
      id: "design-creative-69",
      title: "3D Product Visualization & Animation Artist in Blender",
      description: "Produce high-fidelity 3D models, photorealistic textures, lighting setups, and dynamic 15-second product demo video animations in Blender.",
      skills: ["3D", "Blender", "Motion Graphics", "After Effects", "Product Visualization"],
      budget: "$3,000 - $5,500 Fixed",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.85,
      clientReviews: 33,
      clientSpending: "$160,000+",
      location: "Remote",
      proposalCount: 4,
      urgency: "high",
      source: "99designs",
      projectUrl: "https://99designs.com",
      score: 93,
      scoreReasons: ["3D Blender product animation"]
    },
    {
      id: "content-problogger-70",
      title: "ProBlogger: B2B Enterprise IT Infrastructure & Cybersecurity Writer",
      description: "Author comprehensive, technical SEO-optimized long-form articles covering Microsoft 365 security, hybrid cloud migration, and active directory hardening.",
      skills: ["Content Writing", "Copywriting", "SEO Blogs", "Technical Writing", "Cybersecurity"],
      budget: "$0.15 - $0.25 / word ($400 - $700 / article)",
      currency: "USD",
      hourlyOrFixed: "fixed",
      clientRating: 4.95,
      clientReviews: 54,
      clientSpending: "$280,000+",
      location: "Remote",
      proposalCount: 3,
      urgency: "high",
      source: "ProBlogger",
      projectUrl: "https://problogger.com/jobs",
      score: 94,
      scoreReasons: ["Technical IT & M365 content writing"]
    }
  ];

  return seedJobs.map(job => ({
    ...job,
    sourceStatus: "mock" as const,
    sourceStatusReason: "catalog_seed",
    projectUrl: resolveDirectJobUrl({
      source: job.source,
      title: job.title,
      skills: job.skills,
      projectUrl: job.projectUrl,
      id: job.id
    }),
    scrapeTimestamp: nowISO
  }));
}
